const colors = {
  light: {
    text: "#1a0a0a",
    tint: "#dc2626",
    background: "#fafafa",
    foreground: "#1a0a0a",
    card: "#ffffff",
    cardForeground: "#1a0a0a",
    primary: "#dc2626",
    primaryForeground: "#ffffff",
    primaryDark: "#b91c1c",
    primaryLight: "#fef2f2",
    secondary: "#f8f4f4",
    secondaryForeground: "#5c3333",
    muted: "#f5f0f0",
    mutedForeground: "#9b7c7c",
    accent: "#fde8e8",
    accentForeground: "#7f1d1d",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#f0e0e0",
    input: "#f0e0e0",
    navBg: "#1a0505",
    navText: "#ffffff",
    gradientStart: "#dc2626",
    gradientEnd: "#991b1b",
  },
  radius: 14,
};

export default colors;
